apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-dp-cont
  labels:
    brand: indian
spec:
  replicas: 5
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - todo
  strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  template:
    metadata:
      name: kpod
      labels:
        app: todo
    spec:
      containers:
      - name: new-dp-cont
        image: devopsinsiders/profile:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
    