apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-controller
spec:
  replicas: 10
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - profile
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: profile-pod
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: devopsinsiders/profile:v1
        #image: devopsinsiders/profile:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000