apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    brand: reebok
spec:
  containers:
  - name: nginx-cont
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
